import { User, Store, Role } from './types';

export const USERS: Record<string, User> = {
  kathreen:    {id:'kathreen',    name:'Kathreen Mourad',   firstName:'Kathreen', lastName:'Mourad', initials:'KM', role:'AP_COORDINATOR',      division:'both', email:'kathreen@dossaniparadise.com'},
  anila:       {id:'anila',       name:'Anila Dossani',     firstName:'Anila',    lastName:'Dossani', initials:'AD', role:'AP_SUPERVISOR',        division:'both', email:'anila@dossaniparadise.com'},
  ap:          {id:'ap',          name:'Accounting Dossani', firstName:'Accounting', lastName:'Dossani', initials:'AD', role:'ACCOUNTING',           division:'both', email:'ap@dossaniparadise.com'},
  husain:      {id:'husain',      name:'Husain Virani',     firstName:'Husain',   lastName:'Virani', initials:'HV', role:'FINANCE_MANAGER',      division:'both', email:'husain@dossaniparadise.com'},
  rick_dir:    {id:'rick_dir',    name:'Rick Tharani',      firstName:'Rick',     lastName:'Tharani', initials:'RT', role:'DIRECTOR',             division:'C-Store', email:'rick@dossaniparadise.com'},
  paul:        {id:'paul',        name:'Paul Fernandez',    firstName:'Paul',     lastName:'Fernandez', initials:'PF', role:'DIRECTOR',             division:'Fast Food', email:'paul@dossaniparadise.com'},
  sam:         {id:'sam',         name:'Sam Merchant',      firstName:'Sam',      lastName:'Merchant', initials:'SM', role:'VP',                   division:'both', email:'sam@dossaniparadise.com'},
  armaan:      {id:'armaan',      name:'Armaan Dossani',    firstName:'Armaan',   lastName:'Dossani', initials:'AD', role:'COO',                  division:'both', email:'armaan@dossaniparadise.com'},
  ops:         {id:'ops',         name:'Ops Services',      firstName:'Ops',      lastName:'Services', initials:'OS', role:'OPS_SERVICES_MANAGER', division:'both', email:'ops@dossaniparadise.com'},
  it:          {id:'it',          name:'IT Support',        firstName:'IT',       lastName:'Support', initials:'IT', role:'IT_COORDINATOR',       division:'both', email:'it@dossaniparadise.com'},
  karim:       {id:'karim',       name:'Karim Mawani',      firstName:'Karim',    lastName:'Mawani', initials:'KM', role:'DEVELOPMENT_MANAGER',  division:'both', email:'karim@dossaniparadise.com'},
  rick_tharani:{id:'rick_tharani',name:'Rick Tharani',      firstName:'Rick',     lastName:'Tharani', initials:'RT', role:'AREA_COACH',           division:'C-Store',   region:'East Texas', email:'rick@dossaniparadise.com'},
  jennifer:    {id:'jennifer',    name:'Jennifer Sanders',  firstName:'Jennifer', lastName:'Sanders', initials:'JS', role:'AREA_COACH',           division:'C-Store',   region:'East Texas', email:'jennifer@dossaniparadise.com'},
  vishal:      {id:'vishal',      name:'Vishal Chhetri',    firstName:'Vishal',   lastName:'Chhetri', initials:'VC', role:'AREA_COACH',           division:'C-Store',   region:'West Texas', email:'vishal@dossaniparadise.com'},
  betty:       {id:'betty',       name:'Betty Wilson',      firstName:'Betty',    lastName:'Wilson', initials:'Betty', role:'AREA_COACH',           division:'C-Store',   region:'East Texas', email:'betty@dossaniparadise.com'},
  pedro:       {id:'pedro',       name:'Pedro Alcantar',    firstName:'Pedro',    lastName:'Alcantar', initials:'PA', role:'AREA_COACH',           division:'Fast Food', region:'West Texas', email:'pedro@dossaniparadise.com'},
  waleska:     {id:'waleska',     name:'Waleska Rios',      firstName:'Waleska',  lastName:'Rios', initials:'WR', role:'AREA_COACH',           division:'Fast Food', region:'West Texas', email:'waleska@dossaniparadise.com'},
  dane:        {id:'dane',        name:'Dane Martin',       firstName:'Dane',     lastName:'Martin', initials:'DM', role:'AREA_COACH',           division:'Fast Food', region:'East Texas', email:'dane@dossaniparadise.com'},
  claudia:     {id:'claudia',     name:'Claudia Fernandez', firstName:'Claudia',  lastName:'Fernandez', initials:'CF', role:'AREA_COACH',           division:'Fast Food', region:'West Texas', email:'claudia@dossaniparadise.com'},
  steve:       {id:'steve',       name:'Steve Cardone',     firstName:'Steve',    lastName:'Cardone', initials:'SC', role:'AREA_COACH',           division:'Fast Food', region:'West Texas', email:'steve@dossaniparadise.com'},
  elizabeth:   {id:'elizabeth',   name:'Elizabeth Cruz',    firstName:'Elizabeth',lastName:'Cruz', initials:'EC', role:'AREA_COACH',           division:'Fast Food', region:'West Texas', email:'elizabeth@dossaniparadise.com'},
};

export const STORES: Store[] = [
  // Paradise Quick Stops (Numerical)
  {id:'cs-rt1',  name:'Paradise Quick Stop #01',       division:'C-Store', region:'East Texas', acId:'rick_tharani',directorId:'rick_dir'},
  {id:'cs-rt2',  name:'Paradise Quick Stop #02',       division:'C-Store', region:'East Texas', acId:'rick_tharani',directorId:'rick_dir'},
  {id:'cs-rt3',  name:'Paradise Quick Stop #03',       division:'C-Store', region:'East Texas', acId:'rick_tharani',directorId:'rick_dir'},
  {id:'cs-vc2',  name:'Paradise Quick Stop #04',       division:'C-Store', region:'West Texas', acId:'vishal',      directorId:'rick_dir'},
  {id:'cs-js1',  name:'Paradise Quick Stop #05',       division:'C-Store', region:'East Texas', acId:'jennifer',    directorId:'rick_dir'},
  {id:'cs-js2',  name:'Paradise Quick Stop #06',       division:'C-Store', region:'East Texas', acId:'jennifer',    directorId:'rick_dir'},
  {id:'cs-js3',  name:'Paradise Quick Stop #07',       division:'C-Store', region:'East Texas', acId:'jennifer',    directorId:'rick_dir'},
  {id:'cs-js4',  name:'Paradise Quick Stop #08',       division:'C-Store', region:'East Texas', acId:'jennifer',    directorId:'rick_dir'},
  {id:'cs-js5',  name:'Paradise Quick Stop #09',       division:'C-Store', region:'East Texas', acId:'jennifer',    directorId:'rick_dir'},
  {id:'cs-js6',  name:'Paradise Quick Stop #10',       division:'C-Store', region:'East Texas', acId:'jennifer',    directorId:'rick_dir'},
  {id:'cs-js7',  name:'Paradise Quick Stop #11',       division:'C-Store', region:'East Texas', acId:'jennifer',    directorId:'rick_dir'},
  {id:'cs-bw1',  name:'Paradise Quick Stop #12',       division:'C-Store', region:'East Texas', acId:'betty',       directorId:'rick_dir'},
  {id:'cs-js8',  name:'Paradise Quick Stop #13',       division:'C-Store', region:'East Texas', acId:'jennifer',    directorId:'rick_dir'},
  {id:'cs-vc3',  name:'Paradise Quick Stop #14',       division:'C-Store', region:'West Texas', acId:'vishal',      directorId:'rick_dir'},
  {id:'cs-pqs15',name:'Paradise Quick Stop #15',       division:'C-Store', region:'East Texas', acId:null,          directorId:'rick_dir'},
  {id:'cs-pqs16',name:'Paradise Quick Stop #16',       division:'C-Store', region:'East Texas', acId:null,          directorId:'rick_dir'},

  // Burger Kings (Alphabetical)
  {id:'ff-pa2',  name:'Burger King #27082 Alliance',   division:'Fast Food', region:'West Texas', acId:'pedro',     directorId:'paul'},
  {id:'ff-pa1',  name:'Burger King #22027 Alvord',     division:'Fast Food', region:'West Texas', acId:'pedro',     directorId:'paul'},
  {id:'ff-dm1',  name:'Burger King #23086 Atlanta',    division:'Fast Food', region:'East Texas', acId:'dane',      directorId:'paul'},
  {id:'ff-pa3',  name:'Burger King #27083 Azle',       division:'Fast Food', region:'West Texas', acId:'pedro',     directorId:'paul'},
  {id:'ff-pa4',  name:'Burger King #28626 Bailey Boswell', division:'Fast Food', region:'West Texas', acId:'pedro', directorId:'paul'},
  {id:'ff-dm2',  name:'Burger King #11460 Bonham',     division:'Fast Food', region:'East Texas', acId:'dane',      directorId:'paul'},
  {id:'ff-wr1',  name:'Burger King #26924 Corinth',    division:'Fast Food', region:'West Texas', acId:'waleska',   directorId:'paul'},
  {id:'ff-wr2',  name:'Burger King #28313 Cross Roads',division:'Fast Food', region:'West Texas', acId:'waleska',   directorId:'paul'},
  {id:'ff-wr3',  name:'Burger King #26183 Denton',     division:'Fast Food', region:'West Texas', acId:'waleska',   directorId:'paul'},
  {id:'ff-wr4',  name:'Burger King #3675 Denton',      division:'Fast Food', region:'West Texas', acId:'waleska',   directorId:'paul'},
  {id:'ff-wr5',  name:'Burger King #27028 Gainesville',division:'Fast Food', region:'West Texas', acId:'waleska',   directorId:'paul'},
  {id:'ff-cf1',  name:'Burger King #20671 Greenville', division:'Fast Food', region:'West Texas', acId:'claudia',   directorId:'paul'},
  {id:'ff-dm3',  name:'Burger King #26015 Hooks',      division:'Fast Food', region:'East Texas', acId:'dane',      directorId:'paul'},
  {id:'ff-ec1',  name:'Burger King #27415 Kaufman',    division:'Fast Food', region:'West Texas', acId:'elizabeth', directorId:'paul'},
  {id:'ff-cf2',  name:'Burger King #6460 McKinney',    division:'Fast Food', region:'West Texas', acId:'claudia',   directorId:'paul'},
  {id:'ff-sc1',  name:'Burger King #28174 Melissa',    division:'Fast Food', region:'West Texas', acId:'steve',     directorId:'paul'},
  {id:'ff-ec2',  name:'Burger King #28312 Mesquite',   division:'Fast Food', region:'West Texas', acId:'elizabeth', directorId:'paul'},
  {id:'ff-pa5',  name:'Burger King #28514 Midlothian', division:'Fast Food', region:'West Texas', acId:'pedro',     directorId:'paul'},
  {id:'ff-dm4',  name:'Burger King #10358 Nash',       division:'Fast Food', region:'East Texas', acId:'dane',      directorId:'paul'},
  {id:'ff-dm5',  name:'Burger King #24008 New Boston', division:'Fast Food', region:'East Texas', acId:'dane',      directorId:'paul'},
  {id:'ff-dm6',  name:'Burger King #2390 Paris',       division:'Fast Food', region:'East Texas', acId:'dane',      directorId:'paul'},
  {id:'ff-sc2',  name:'Burger King #4851 Plano (Coit)',division:'Fast Food', region:'West Texas', acId:'steve',     directorId:'paul'},
  {id:'ff-cf3',  name:'Burger King #13192 Plano (Ohio)',division:'Fast Food',region:'West Texas', acId:'claudia',   directorId:'paul'},
  {id:'ff-cf4',  name:'Burger King #27958 Quinlan',    division:'Fast Food', region:'West Texas', acId:'claudia',   directorId:'paul'},
  {id:'ff-cf5',  name:'Burger King #24875 Royse City', division:'Fast Food', region:'West Texas', acId:'claudia',   directorId:'paul'},
  {id:'ff-wr6',  name:'Burger King #27084 Saginaw',    division:'Fast Food', region:'West Texas', acId:'waleska',   directorId:'paul'},
  {id:'ff-ec3',  name:'Burger King #28683 Sunnyvale',  division:'Fast Food', region:'West Texas', acId:'elizabeth', directorId:'paul'},
  {id:'ff-cf6',  name:'Burger King #25198 Terrell',    division:'Fast Food', region:'West Texas', acId:'claudia',   directorId:'paul'},
  {id:'ff-sc3',  name:'Burger King #9723 The Colony',  division:'Fast Food', region:'West Texas', acId:'steve',     directorId:'paul'},

  // Others
  {id:'cs-vc1',  name:'7-Eleven #39787 Riverfront',   division:'C-Store', region:'West Texas', acId:'vishal',      directorId:'rick_dir'},
  {id:'ff-dm7',  name:'Subway #22410',                 division:'Fast Food', region:'East Texas', acId:'dane',      directorId:'paul'},
  {id:'cs-nrm',  name:'Nashville Road Mart',           division:'C-Store', region:'East Texas', acId:null,          directorId:'rick_dir'},
  {id:'cs-vc4',  name:'Scarborough Travel Stop',       division:'C-Store', region:'West Texas', acId:'vishal',      directorId:'rick_dir'},
  {id:'cs-vc5',  name:'Scarborough Car Wash',          division:'Car Wash', region:'West Texas', acId:'vishal',      directorId:'rick_dir'},
];
